version: "3.9"
services:
  assetto_server:
    image: germanrcuriel/assetto-corsa-server
    container_name: ac_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - STEAM_USER=coolifysaqi
      - STEAM_PASSWORD=Ea9CE5mAYvPUEfd
      - AC_SERVER_NAME=Coolify AC Server
      - AC_PASSWORD=yourpassword
      - AC_ADMIN_PASSWORD=youradminpass
    ports:
      - "8081:8081"
      - "9600:9600"
      - "9600:9600/udp"
      - "50041:50041"
      - "50042:50042"
    volumes:
      - ./ac_data:/steamapps
