version: "3.9"
services:
  assetto_server:
    image: mbround18/assetto-server
    container_name: ac_server
    ports:
      - "9600:9600/udp"
      - "9601:9601/udp"
      - "8081:8081"
    volumes:
      - ./cfg:/assetto/server/cfg
      - ./content:/assetto/server/content
    environment:
      - AC_PASSWORD=yourpassword
      - ADMIN_PASSWORD=youradminpass